version: '3.4'

networks:
  twitterclonenet:
    driver: bridge


services:
  twitterclonedb:
    container_name: TwitterCloneDb
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=myStong_Password123%
    networks:
      - twitterclonenet
  twittercloneapi:
    container_name: TwitterCloneAPI
    image: ${DOCKER_REGISTRY-}twittercloneapi
    build:
      context: .
      dockerfile: TwitterCloneAPI/Dockerfile
    ports:
      - 8081:443
    depends_on:
      - twitterclonedb
    networks:
      - twitterclonenet
    environment:
      - Docker_ConnectionString=Server=twitterclonedb,1433;Database=twitterclone;User Id=sa;Password=myStong_Password123%;TrustServerCertificate=True;


